# Generated by Django 5.2.7 on 2025-11-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.TextField()),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('hardware_concurrency', models.IntegerField(blank=True, null=True)),
                ('device_memory', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_width', models.IntegerField(blank=True, null=True)),
                ('screen_height', models.IntegerField(blank=True, null=True)),
                ('color_depth', models.IntegerField(blank=True, null=True)),
                ('downlink', models.CharField(blank=True, max_length=20, null=True)),
                ('effective_type', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
