# Generated by Django 5.2.7 on 2025-11-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_systemstatus_delete_systemreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstatus',
            name='download_Mbps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='ping_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='upload_Mbps',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
